# Generated by Django 4.2.16 on 2026-07-09 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "account_group",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("initial_balance", models.BigIntegerField(default=0)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "target_weight",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
            ],
            options={
                "verbose_name_plural": "categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RebalanceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_weight", models.DecimalField(decimal_places=2, max_digits=5)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rebalance_entry",
                        to="portfolio.category",
                    ),
                ),
            ],
            options={
                "ordering": ["category__name"],
            },
        ),
        migrations.CreateModel(
            name="RebalanceStockHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=10)),
                ("stock_name", models.CharField(blank=True, max_length=100)),
                ("old_category_name", models.CharField(blank=True, max_length=50)),
                ("new_category_name", models.CharField(blank=True, max_length=50)),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("ADDED", "추가"),
                            ("UPDATED", "수정"),
                            ("DELETED", "삭제"),
                        ],
                        max_length=10,
                    ),
                ),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "rebalance stock histories",
                "ordering": ["-changed_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stocks",
                        to="portfolio.category",
                    ),
                ),
            ],
            options={
                "ordering": ["ticker"],
            },
        ),
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trade_type",
                    models.CharField(
                        choices=[("BUY", "매수"), ("SELL", "매도")], max_length=4
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("price", models.PositiveIntegerField(help_text="1주당 체결 단가")),
                ("fee", models.PositiveIntegerField(default=0)),
                ("tax", models.PositiveIntegerField(default=0)),
                ("traded_on", models.DateField()),
                ("memo", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trades",
                        to="portfolio.account",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trades",
                        to="portfolio.stock",
                    ),
                ),
            ],
            options={
                "ordering": ["-traded_on", "-id"],
            },
        ),
        migrations.CreateModel(
            name="RebalanceStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_weight",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "rebalance_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stocks",
                        to="portfolio.rebalancecategory",
                    ),
                ),
                (
                    "stock",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rebalance_entry",
                        to="portfolio.stock",
                    ),
                ),
            ],
            options={
                "ordering": ["rebalance_category__category__name", "stock__ticker"],
            },
        ),
        migrations.CreateModel(
            name="RebalanceCategoryHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("new_weight", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "change_type",
                    models.CharField(
                        choices=[("CREATED", "생성"), ("UPDATED", "수정")],
                        max_length=10,
                    ),
                ),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rebalance_histories",
                        to="portfolio.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "rebalance category histories",
                "ordering": ["-changed_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="InstrumentAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("krx_ticker", models.CharField(blank=True, max_length=10)),
                ("naver_symbol", models.CharField(blank=True, max_length=10)),
                ("yahoo_symbol", models.CharField(blank=True, max_length=20)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stock",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instrument_alias",
                        to="portfolio.stock",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "instrument aliases",
                "ordering": ["stock__ticker"],
            },
        ),
        migrations.CreateModel(
            name="CashFlow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "flow_type",
                    models.CharField(
                        choices=[("DEPOSIT", "입금"), ("WITHDRAW", "출금")],
                        max_length=10,
                    ),
                ),
                ("amount", models.PositiveBigIntegerField()),
                ("occurred_on", models.DateField()),
                ("memo", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cashflows",
                        to="portfolio.account",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_on", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price_date", models.DateField()),
                ("close_price", models.DecimalField(decimal_places=4, max_digits=16)),
                ("source", models.CharField(default="pykrx", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="portfolio.stock",
                    ),
                ),
            ],
            options={
                "ordering": ["-price_date", "stock__ticker"],
                "unique_together": {("stock", "price_date")},
            },
        ),
        migrations.CreateModel(
            name="HoldingSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("as_of_date", models.DateField()),
                ("quantity", models.PositiveIntegerField()),
                ("avg_price", models.PositiveIntegerField()),
                ("current_price", models.PositiveIntegerField()),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holding_snapshots",
                        to="portfolio.account",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holding_snapshots",
                        to="portfolio.stock",
                    ),
                ),
            ],
            options={
                "ordering": ["-as_of_date", "stock__ticker"],
                "unique_together": {("account", "stock", "as_of_date")},
            },
        ),
        migrations.CreateModel(
            name="AccountSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("as_of_date", models.DateField()),
                ("cash_balance", models.PositiveBigIntegerField(default=0)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="portfolio.account",
                    ),
                ),
            ],
            options={
                "ordering": ["-as_of_date", "-id"],
                "unique_together": {("account", "as_of_date")},
            },
        ),
    ]
