# Generated by Django 4.2.30 on 2026-07-15 15:55

from django.db import migrations, models


DEFAULT_JONGHAP_ONLY_TICKERS = {
    "AGNC",
    "NLY",
    "STWD",
    "RITM",
    "ARR",
    "TWO",
    "CIM",
    "BXMT",
    "MFA",
    "PMT",
    "ORC",
    "IVR",
    "EFC",
    "ABR",
}


def seed_jonghap_flags(apps, schema_editor):
    Stock = apps.get_model("portfolio", "Stock")
    Account = apps.get_model("portfolio", "Account")

    Stock.objects.filter(ticker__in=DEFAULT_JONGHAP_ONLY_TICKERS).update(requires_jonghap_account=True)

    for account in Account.objects.all():
        label = f"{account.account_group} {account.name}".replace(" ", "")
        if "종합매매" in label:
            account.is_jonghap = True
            account.save(update_fields=["is_jonghap"])


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="is_jonghap",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="stock",
            name="requires_jonghap_account",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(seed_jonghap_flags, migrations.RunPython.noop),
    ]
